begin

try {
    import 'c'
} catch err {
    fun f() {
        import 'c'
    }
    f()
}

end
